"""empty message

Revision ID: 095d5d77c1f1
Revises: 
Create Date: 2024-05-07 20:18:30.418715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095d5d77c1f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizensDetails',
    sa.Column('licenseId', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('dateIssued', sa.Date(), nullable=True),
    sa.Column('fatherName', sa.String(length=255), nullable=True),
    sa.Column('dateofBirth', sa.Date(), nullable=True),
    sa.Column('expirationDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('licenseId')
    )
    op.create_table('officer',
    sa.Column('officerId', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('badgeNumber', sa.String(length=255), nullable=True),
    sa.Column('rank', sa.String(length=255), nullable=True),
    sa.Column('assignedLocation', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('officerId')
    )
    op.create_table('rulesAndRegulations',
    sa.Column('rulesId', sa.String(length=255), nullable=False),
    sa.Column('rulecategory', sa.String(length=255), nullable=True),
    sa.Column('ruleDesc', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('rulesId')
    )
    op.create_table('users',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('usertype', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicle',
    sa.Column('vehicleId', sa.String(length=255), nullable=False),
    sa.Column('RegistrationId', sa.Integer(), nullable=True),
    sa.Column('RegistrationNumber', sa.String(length=255), nullable=True),
    sa.Column('registrationdate', sa.Date(), nullable=True),
    sa.Column('vehicleType', sa.String(length=255), nullable=True),
    sa.Column('vehicleMake', sa.String(length=255), nullable=True),
    sa.Column('VehicleModel', sa.String(length=255), nullable=True),
    sa.Column('ChasisNumber', sa.String(length=255), nullable=True),
    sa.Column('EngineNumber', sa.String(length=255), nullable=True),
    sa.Column('VehicleCategory', sa.String(length=255), nullable=True),
    sa.Column('VehicleCustomtaxId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('vehicleId')
    )
    op.create_table('vehicleowner',
    sa.Column('registrationNumber', sa.String(length=255), nullable=False),
    sa.Column('vehicleid', sa.String(length=255), nullable=True),
    sa.Column('citizenId', sa.String(length=255), nullable=True),
    sa.Column('licenseId', sa.String(length=255), nullable=True),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('RegistrationExp', sa.Date(), nullable=True),
    sa.Column('RegistrationStatus', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('registrationNumber')
    )
    op.create_table('challanhistory',
    sa.Column('challannumber', sa.String(length=255), nullable=False),
    sa.Column('registrationNumber', sa.String(length=255), nullable=True),
    sa.Column('violationReason', sa.String(length=255), nullable=True),
    sa.Column('violationId', sa.String(length=255), nullable=True),
    sa.Column('chargedAmount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dateIssued', sa.Date(), nullable=True),
    sa.Column('issuedLocation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['registrationNumber'], ['vehicleowner.registrationNumber'], ),
    sa.PrimaryKeyConstraint('challannumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challanhistory')
    op.drop_table('vehicleowner')
    op.drop_table('vehicle')
    op.drop_table('users')
    op.drop_table('rulesAndRegulations')
    op.drop_table('officer')
    op.drop_table('citizensDetails')
    # ### end Alembic commands ###
