"""empty message

Revision ID: 41be040c8268
Revises: f6b547ad8b5d
Create Date: 2024-04-06 22:26:15.101099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41be040c8268'
down_revision = 'f6b547ad8b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizensDetails',
    sa.Column('licenseId', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('dateIssued', sa.Date(), nullable=True),
    sa.Column('fatherName', sa.String(length=255), nullable=True),
    sa.Column('dateofBirth', sa.Date(), nullable=True),
    sa.Column('expirationDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('licenseId')
    )
    op.create_table('rulesAndRegulations',
    sa.Column('rulesId', sa.String(length=255), nullable=False),
    sa.Column('rulecategory', sa.String(length=255), nullable=True),
    sa.Column('ruleDesc', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('rulesId')
    )
    op.drop_table('rulesandregulations')
    with op.batch_alter_table('vehicleowner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('licenseId', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicleowner', schema=None) as batch_op:
        batch_op.drop_column('licenseId')

    op.create_table('rulesandregulations',
    sa.Column('rulesId', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('rulecategory', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ruleDesc', mysql.VARCHAR(length=225), nullable=True),
    sa.PrimaryKeyConstraint('rulesId'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('rulesAndRegulations')
    op.drop_table('citizensDetails')
    # ### end Alembic commands ###
