"""Second only vehiclereg

Revision ID: 79defd375eb5
Revises: 
Create Date: 2024-03-28 17:52:32.339299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79defd375eb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('VehicleId', sa.Integer(), nullable=True),
    sa.Column('registrationNumber', sa.String(length=50), nullable=True),
    sa.Column('registrationDate', sa.Date(), nullable=True),
    sa.Column('registrationExpiryDate', sa.Date(), nullable=True),
    sa.Column('registrationStatus', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_registration')
    # ### end Alembic commands ###
