"""Initital migrate for database designed
Revision ID: aabe6ec313d9
Revises: 79defd375eb5
Create Date: 2024-04-01 20:47:55.868220
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aabe6ec313d9'
down_revision = '79defd375eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer',
    sa.Column('officerId', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('badgeNumber', sa.String(length=255), nullable=True),
    sa.Column('rank', sa.String(length=255), nullable=True),
    sa.Column('assignedLocation', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('officerId')
    )
    op.create_table('users',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('usertype', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('vehicle',
    sa.Column('vehicleId', sa.String(length=255), nullable=False),
    sa.Column('RegistrationId', sa.Integer(), nullable=True),
    sa.Column('RegistrationNumber', sa.String(length=255), nullable=True),
    sa.Column('registrationdate', sa.Date(), nullable=True),
    sa.Column('vehicleType', sa.String(length=255), nullable=True),
    sa.Column('vehicleMake', sa.String(length=255), nullable=True),
    sa.Column('VehicleModel', sa.String(length=255), nullable=True),
    sa.Column('ChasisNumber', sa.String(length=255), nullable=True),
    sa.Column('EngineNumber', sa.String(length=255), nullable=True),
    sa.Column('VehicleCategory', sa.String(length=255), nullable=True),
    sa.Column('VehicleCustomtaxId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('vehicleId')
    )
    op.create_table('vehicleowner',
    sa.Column('registrationNumber', sa.String(length=255), nullable=False),
    sa.Column('vehicleid', sa.String(length=255), nullable=True),
    sa.Column('citizenId', sa.String(length=255), nullable=True),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('RegistrationExp', sa.Date(), nullable=True),
    sa.Column('RegistrationStatus', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('registrationNumber')
    )
    op.create_table('challanhistory',
    sa.Column('challannumber', sa.String(length=255), nullable=False),
    sa.Column('registrationNumber', sa.String(length=255), nullable=True),
    sa.Column('violationReason', sa.String(length=255), nullable=True),
    sa.Column('violationId', sa.String(length=255), nullable=True),
    sa.Column('chargedAmount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dateIssued', sa.Date(), nullable=True),
    sa.Column('issuedLocation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['registrationNumber'], ['vehicleowner.registrationNumber'], ),
    sa.PrimaryKeyConstraint('challannumber')
    )
    op.drop_table('vehicle_registration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_registration',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('VehicleId', sa.INTEGER(), nullable=True),
    sa.Column('registrationNumber', sa.VARCHAR(length=50), nullable=True),
    sa.Column('registrationDate', sa.DATE(), nullable=True),
    sa.Column('registrationExpiryDate', sa.DATE(), nullable=True),
    sa.Column('registrationStatus', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('challanhistory')
    op.drop_table('vehicleowner')
    op.drop_table('vehicle')
    op.drop_table('users')
    op.drop_table('officer')
    # ### end Alembic commands ###