"""Initial migration

Revision ID: f6b547ad8b5d
Revises: 9349e9ca0e38
Create Date: 2024-04-03 09:49:39.781611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6b547ad8b5d'
down_revision = '9349e9ca0e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rulesAndRegulations',
    sa.Column('rulesId', sa.String(length=255), nullable=False),
    sa.Column('rulescategory', sa.String(length=255), nullable=True),
    sa.Column('ruleDesc', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('rulesId')
    )
    op.drop_table('rulesandregulations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rulesandregulations',
    sa.Column('rulesId', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('rulecategory', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ruleDesc', mysql.VARCHAR(length=225), nullable=True),
    sa.PrimaryKeyConstraint('rulesId'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('rulesAndRegulations')
    # ### end Alembic commands ###
